#!/bin/bash
#
# Ara Monitor 
# description: Foo server
# Copyright (c) 2013, Change Jeong. 
#
# Author : Changje Jeong <rodumani@sparcs.org> 
# 
# Start the service

monitor_directory=./
crawler=$monitor_directory/ara.py

start() {
		if [ "$(pidof aracrawler)" ]
		then
			echo "Ara monitor is already running"
			exit 1
		else 
			echo "Starting Ara monitor"
			$crawler
			echo "Ara monitor startup"
		fi
}
# Restart the service 
stop() {
        echo "Stopping Ara Monitor"
		if [ "$(pidof aracrawler)" ]
		then
			kill $(pidof aracrawler)
			sleep 1
			if [ "$(pidof aracrawler)" ]
			then
				kill -9 $(pidof aracrawler)
			fi 
			echo "Ara monitor stopped"
		else 
			echo "Ara monitor is not running"
		fi 
		killall twistd
}
### main logic ###
case "$1" in
  start)
        start
        ;;
  stop)
        stop
        ;;
  restart|reload|condrestart)
        stop
        start
        ;;
  *)
        echo $"Usage: $0 {start|stop|restart|reload}"
        exit 1
esac
exit 0
